### ISSUE TITLE
Support protected switches

### ISSUE THREAD

**Issue by davidlb** [domoticz/Reacticz#10]
Protected switch needs password to get switched. After some tests, it can be managed with JSON parameter 'passcode'.  With MQTT, password for switches is totally ignored and protected switches behaves as normal switch (and so in Reacticz).

Passcode is globally manage at Domoticz level so we can manage it in the same way in reacticz (just a simple switch password field on the settings page).

**Comment by t0mg** [comment]
So if I understand correctly, using mqtt bypasses the need for a password? Why would we need to use it then?

**Comment by davidlb** [comment]
In fact, security should be managed on Domoticz side so I close this request for now.

**Comment by t0mg** [comment]
I agree :) Feel free to reopen the issue once the Domoticz side is ready !
