### ISSUE TITLE
Draft for secure Reacticz wiki entry

### ISSUE THREAD

**Issue by bru1979** [domoticz/Reacticz#11]
## **Securing Domoticz, Reacticz and MQTT websockets**

Requirements: a public FQDN pointing to your Domoticz host

First of all, secure Domoticz and Reacticz URLs with SSL (for free) as per wiki
https://www.domoticz.com/wiki/Native_secure_access_with_Lets_Encrypt

Secure also MQTT with the same free SSL cert. Add to the new websockets listener, explained here 
https://www.domoticz.com/forum/viewtopic.php?t=14941&start=60#p115273
the following lines:

```
certfile /etc/letsencrypt/live/put_your_FQDN_here/cert.pem
cafile /etc/letsencrypt/live/put_your_FQDN_here/chain.pem
keyfile /etc/letsencrypt/live/put_your_FQDN_here/privkey.pem
password_file /etc/mosquitto/pwfile
```

Add a user and a password to Mosquitto
https://mosquitto.org/man/mosquitto_passwd-1.html

`sudo mosquitto_passwd -c /etc/mosquitto/pwfile put_your_USERNAME_here`

Restart both Mosquitto and Domoticz then add to Reacticz the secured websockets URL
`wss://put_your_FQDN_here:put_your_WEBSOCKETS_LISTENER_here`

and enable authentication.

Add secured URL to Domoticz section

**Comment by bru1979** [comment]
feel free to add/edit/delete! :)

**Comment by t0mg** [comment]
This is great, thanks @bru1979 :)
I've added this to the Tips&Tricks page in the wiki and updated the Readme to link to it as well.

**Comment by t0mg** [comment]
@bru1979 the latest commit c3ac2b6 provides full resource caching with a service worker (which should make the app start faster), but that'll only work with secure host (https). Given that you have that setup, would you mind installing v0.1.15 and letting me know if it works? Once the cache is active a simple test you can do is killing and restarting reacticz with airplane mode on your device. Thanks!
