### ISSUE TITLE
device Offline

### ISSUE THREAD

**Issue by johnx102** [domoticz/Reacticz#13]
hi, I've juste install the latest version, i have a little problem,
i don't understand why reacticzwork good with scene, but when i wad to add a device, it's show me offline ....
Do reacticz just work with scene ad group ??

Thanks for the help and sorry for my english ;)

**Comment by t0mg** [comment]
Sounds like you have configuration issues (probably with the MQTT broker). Did you follow the [instructions](https://github.com/domoticz/Reacticz#requirements) and configure websockets on it ?

Best way to get help on this is to ask on domoticz forums (for example [here](https://www.domoticz.com/forum/viewtopic.php?f=38&t=14941)).

**Comment by johnx102** [comment]
Hi, thank's for the quick answer.
Normally web socket is good, i follow instruction on your github, and seem to be ok.
ws://****:1884 say connected and is green .... Scene is working if it can help you ....
Or even when web socket is not enabled ha can say connected ??

**Comment by johnx102** [comment]
Ok thank's a lot i understand it's my bad, i forgot to add mqtt client in domoticz.
Now it's good .
Thank's again, just have to play for do a good template ;)

**Comment by t0mg** [comment]
Great, have fun!
