### ISSUE TITLE
No return of information / Domoticz 2020.2

### ISSUE THREAD

**Issue by Labra54** [domoticz/Reacticz#31]
HI,

Withe the new update of Domoticz 2020.2, i have no return in the page of Reactiz of my action.
(The button have not the color)

The order is good transmitting to domoticz. The action is ok.

Is there a modification in Reactiz do to to have this information ?

Thanks

**Comment by Labra54** [comment]
It's solve.
In the new version, the option of material MQTT "Prevent Loop:" is True value.
With the False value it's OK !

**Comment by t0mg** [comment]
Yes the option introduced in domoticz 2020.2 allows to revert back to the old behavior and keep Reacticz working. According to @gizmocuz this is only temporary tough and in the long term the option will disappear. At that point Reacticz will stop working unless someone writes the necessary changes for it to use json for state polling on all devices currently relying on mqtt.

Cheers,
