### ISSUE TITLE
Rain widget behaving unexpected in Edge on Windows 10 

### ISSUE THREAD

**Issue by t0mg** [domoticz/Reacticz#5]
_From @Sneeuwtijger on February 6, 2017 13:9_

Rain Widget scaling is not as expected and different from for instance Weatherstation, see image
![reactiz windows 10 edge rain widget behaving unexpected](https://cloud.githubusercontent.com/assets/24943584/22648217/e6082a38-ec75-11e6-8ede-fec69e524e28.png)
 

_Copied from original issue: t0mg/reacticz#62_

**Comment by t0mg** [comment]
I think it's expected. In your screenshot, the icon for the rain is larger because it scales with the widget, and you rain widget is taller than the weather widget. Try giving both widgets the same size and the icon should roughly be the same size (roughly because I think there is a discrepancy in the image/text space ratio used in these widgets). 

Somewhere in the repo comments, we discussed topping the size of the icons to a max value, but the issue was never created.

Also note that the icon for rain gauge has changed recently :)

**Comment by t0mg** [comment]
_From @Sneeuwtijger on February 6, 2017 16:53_

I will update to the latest version, I thought is was - this is on 0.1.6 but maybe I have to clear cache. Will try to make them equal in size and see.

**Comment by t0mg** [comment]
_From @gerard33 on February 6, 2017 21:56_

Will probably be the same SVG issue as described in https://github.com/t0mg/reacticz/issues/61#issuecomment-277826594.

**Comment by t0mg** [comment]
_From @Sneeuwtijger on February 7, 2017 18:36_

Reacticz 0.1.7 - new rain gauge icon - spacing seems a bit off , new screen dump : 
![reactiz windows 10 edge rain widget behaving unexpected 2](https://cloud.githubusercontent.com/assets/24943584/22705649/b1bfa2f4-ed6c-11e6-9c82-628231a0c98d.png)

**Comment by t0mg** [comment]
Ok thanks. Looks like a CSS issue then, maybe some unsupported flexbox property.

**Comment by t0mg** [comment]
_From @Sneeuwtijger on February 8, 2017 11:0_

About Flexbox cross browser - maybe this blog has some info https://philipwalton.com/articles/normalizing-cross-browser-flexbox-bugs/, it also refers to a repo on Github with Flexbox issues

**Comment by t0mg** [comment]
_From @Sneeuwtijger on February 8, 2017 16:58_

A screenshot with the new Rainmeter icon , just to be correct
![reacticz issue - rainmeter](https://cloud.githubusercontent.com/assets/24943584/22747733/27774b58-ee28-11e6-93e6-2e729746f532.png)

**Comment by t0mg** [comment]
Hey @Sneeuwtijger, is this still happening? I don't have any Windows/Edge device to test at home :/

**Comment by Sneeuwtijger** [comment]
I will test It asap, let you know ;)

**Comment by Sneeuwtijger** [comment]
Problem is solved - icons are displayed correctly, thx ;)

**Comment by t0mg** [comment]
Cool!
